### ISSUE TITLE
Carrier and group restriction don't work

### ISSUE THREAD

**Issue by getdatakick** [thirtybees/custompayments#3]
Carrier and groups restriction don't work when there is more then one custom payments method defined. 

*Reprosteps:*

1. have 2 carriers
2. create custom payment method, and restrict it to first carrier
3. create another custom payment method and restrict it to second carrier
4. test checkout process

*Expected result* - only one payment method should be displayed, depending on selected carrier
 
*Actual result* - both custom payments method are displayed, regardless of selected carrier

**Comment by RaptorX** [comment]
Hi there.

I wanted to confirm something: this issue seems to be closed and merged but I updated to latest 1.0.6 and still present this problem.

Was this merged with 1.0.6 or will be released on next version?

Thanks!

**Comment by getdatakick** [comment]
The fix will be part of next release of *custompayments* module, not thirtybees core. I'll release it right away
