### ISSUE TITLE
Order Discount not applied to totals 

### ISSUE THREAD

**Issue by palo** [thirtybees/custompayments#5]
I'm testing the module in Thirty Bees 1.1.0 and this feature doesn't seem to be working.
The cart rule is listed under the order in the back office but the final price is given without discount.
Can someone confirm this issue?

**Comment by palo** [comment]
The discount wasn't applied because it was restricted by n uses per user.
But, if all limits are removed, the discount gets active by default regardless of the payment method.
How to use this feature correctly?

**Comment by getdatakick** [comment]
I can't reproduce the problem.

- cart rule is correctly applied when custom payment option is used
- cart rule is NOT automatically applied when other payment option is used
- customer can still manually add cart rule
