### ISSUE TITLE
Doesn't ask for card number

### ISSUE THREAD

**Issue by unbranched** [thirtybees/custompayments#6]
Maybe I'm missing something, I just did a test payment in my shop choosing this option. When I click the button "Confirm my order" it just says ok paid and two confirmation email are sent.

**Comment by unbranched** [comment]
Oh I notice just now that one menu item is "Car**t** type", not "Car**d** type" ... that's why I asked this. The module icon is confusing too...

You can close this issue if this module is not supposed to be used for credit card payments.

**Comment by getdatakick** [comment]
Indeed, custompayments module is not for card payments. It's a generic payment solution for offline type of payments. For example, you can use it to offer 'Cash on delivery' payment option, etc.
