### ISSUE TITLE
Module payment

### ISSUE THREAD

**Issue by croquete1** [thirtybees/custompayments#7]
it would be awesome if  when we create another payment method, it resumes like it does on Bankwire...
![imagem](https://user-images.githubusercontent.com/16768315/203313366-df2c5dac-ac9f-417a-b87e-685f0a0903e4.png)
![imagem](https://user-images.githubusercontent.com/16768315/203313424-e2d4d5ac-567b-4dda-b686-d73573c3ae4c.png)

**Comment by getdatakick** [comment]
I guess you are talking about [custompayments](https://github.com/thirtybees/custompayments) module?

**Comment by croquete1** [comment]
yess

I was looking and I see there is some type of code and %value% or something...
but when selecting other method, the button for finalize payment is different

**Comment by getdatakick** [comment]
There is placeholder `%total%` that you can use in custom payment description. It will be replaced with actual amount.

Not sure what you mean by "button for finalize payment is different"

**Comment by croquete1** [comment]
this is by bankwire module:
![imagem](https://user-images.githubusercontent.com/16768315/203342328-ad30cdd6-ec38-4819-bd33-66ea7ab62aad.png)

this is by other method of payment here in Portugal, it´s MBway:
![imagem](https://user-images.githubusercontent.com/16768315/203342563-5bcd547e-baa2-4567-8edc-2ee6e98f3e66.png)

**Comment by getdatakick** [comment]
This is theme issue, not a module one. 

Your theme probably contains custom override for bankwire module templates, but does not include override for `custompayment` module template, so the default module template is used:

https://github.com/thirtybees/custompayments/blob/master/views/templates/front/payment_execution.tpl

You should override this template for your theme, and adjust it to your needs.

**Comment by getdatakick** [comment]
I have created enhancement request for niara theme thirtybees/niara#62 but that will not help you if you are using different theme

**Comment by croquete1** [comment]
im using Niara theme
![imagem](https://user-images.githubusercontent.com/16768315/203351142-3ee28448-84ae-427e-bfa5-31f067a623af.png)

thanks for all the help
